### ISSUE TITLE
Unable to configure your app.

### ISSUE THREAD

**Issue by possomcohen** [oniatsu/HotSwitch#13]
Hello. I installed your HotSwitch app. I allowed all permission in Sys Pref. However, I am unable to configure the key registrations to apps, etc. All I see is the window when I press Control-Tab keys. Assistance requested. Thank you very much.
![Screen Shot 2020-10-20 at 3 23 44 PM](https://user-images.githubusercontent.com/24848225/96532406-53a58080-12e8-11eb-8442-e3b98ecd69e2.jpg)

**Comment by oniatsu** [comment]
Thanks for your report.
The bug is same to this issue. To fix it manually, restart the app a few times.
https://github.com/oniatsu/HotSwitch/issues/10#issuecomment-651068189
