### ISSUE TITLE
Crashes on monterey

### ISSUE THREAD

**Issue by asyncee** [oniatsu/HotSwitch#15]
Hi, i love HotSwitch but it constantly crashes when trying to switch between windows or checking for updates.

**Comment by oniatsu** [comment]
I created [HotSwitch-HS](https://github.com/oniatsu/HotSwitch-HS) that is substitution of HotSwitch.

HotSwitch don't work on macOS Monterey now.
If you want to use HotSwitch on macOS monterey, use HotSwitch-HS.

It is difficult that I maintain HotSwitch now, because HotSwitch is written by Obj-C and is hard to understand codes.

![preview](https://user-images.githubusercontent.com/5919569/139591542-a4f22e7f-2f37-4c7d-a20f-7fa94df13acb.png)

**Comment by asyncee** [comment]
Thank you very much, it works perfectly. The best window switcher ever. Just as a side note — "arrow-less" navigation in `HS` version is not supported yet? I mean when previous window is remembered and automatically selected when `Panel` widget is presented, so it is possible to switch between two recent windows just by using `cmd + .`.

Anyway, thank you for implementing new version!

**Comment by oniatsu** [comment]
Thank you for check!
I expected that two stroke keys using `cmd + .` + `return` switches the previous window in the situation.
Is this answer correct to the question?

But I recommend the using two apps for different purposes.
- Switching the previous window: cmd + tab (macOS default or [AltTab](https://github.com/lwouis/alt-tab-macos) or [HyperSwitch](https://bahoom.com/hyperswitch) ) 
- Switching any window you forget the position: HotSwitch-HS

**Comment by asyncee** [comment]
Two stroke keys using `cmd + .` + `return` does not switch to the previous window in HS version for me. Actually, i can use `cmd + tab` for sure, just got used to `cmd + .` + `return`. Thanks again :)

**Comment by oniatsu** [comment]
Perhaps, it is bug.

HotSwitch(-HS) expects that it selects second window like below image when panel is open.

![preview](https://user-images.githubusercontent.com/5919569/139619210-b4215c01-a1f8-41db-ad41-34a1882f13bc.png)

The second window means previous one. If the selected window is first one, it may be bug.

**Comment by asyncee** [comment]
It looks like that for me:

![image](https://user-images.githubusercontent.com/701191/139637432-7755a07c-a81b-4038-a145-26a2b5a8a638.png)

You may notice that shortcut keys are also missing.

**Comment by oniatsu** [comment]
> You may notice that shortcut keys are also missing.

Does not the shortcut key appear even if you registered the key?

You can registering a key by this way.
1. Open panel by sending `cmd + .`
2. Select any row by sending `tab`, `shift+tab`, `down` or `up`.
3. Register any key by sending a character key such as `a`, `b` or `c`, etc.

> Regarding the bug: switching between windows in new version does change the selection, i.e i switch to "iTerm" then it will be currently selected instead of previous window.

I think it is bug.

For instance, HotSwitch(-HS) expects these working.
1. For example, current focused window is Safari, and previous window is Mail.
2. Open HotSwitch(-HS) panel.
3. The panel shows Safari at first and Mail at second.
4. The panel's selection row is Mail at second. It means previous window.
5. If you type `return`, the selected Mail's window at second is focused.

**Comment by asyncee** [comment]
Registering a key is not working for me (i followed your instructions exactly) — no reaction. Log output is a list of `Enabled / Disabled key` records.

Switching between windows for me looks like that:

1. Current focused window is Safari and previous window is Mail
2. Open panel
3. The panel shows Safari and Mail
4. Selection is on Safari
5. Switch to Mail using arrow key and `return`
6. Open panel
7. Mail is selected instead of Safari

So the selection follows currently selected window, not previous one.

**Comment by oniatsu** [comment]
I missed a description a little.

> You can registering a key by this way.

The correct steps is here.

1. Open panel by sending `cmd + .`
2. Select any row by sending `tab`, `shift+tab`, `down` or `up`.
3. Change registration mode by sending `space`. (Added)
3. Register any key by sending a character key such as `a`, `b` or `c`, etc.

> Switching between windows for me looks like that:

Thanks.
That is bug, but I don't met the probrem yet. I will pay attention it to find the cause.

**Comment by asyncee** [comment]
I can confirm that registering a key now works by using `space`. Thanks!

**Comment by oniatsu** [comment]
I added some description to register keys to window on lists. [#Usage](https://github.com/oniatsu/HotSwitch-HS#usage)
