### ISSUE TITLE
OSX: Catalina — window titles are not shown

### ISSUE THREAD

**Issue by asyncee** [oniatsu/HotSwitch#9]
Hello, i have upgraded to Catalina release and do not see window titles, so i can not differentiate windows anymore.

Previous output:

```
Pycharm - Project 1
Pycharm - Project 2
```

Current output:

```
Pycharm
Pycharm
```

**Comment by oniatsu** [comment]
Thank you for your report.
I have not checked it on Catalina yet.

Every windows does not show its title, does it?

**Comment by asyncee** [comment]
True. On previous macos version format was like `<app name> <title>` and now only `<app name>` is displayed.

**Comment by oniatsu** [comment]
I fixed it on v1.18.
https://github.com/oniatsu/HotSwitch/commit/fedb33931f6d2dc9d532744d1bcaa279ee7a94be

You can upgrade it on a app menu "Check for Updates...".
You need another permission "Screen Recording" to show window titles.
https://github.com/oniatsu/HotSwitch#requirements

**Comment by asyncee** [comment]
It is working again. Thank you very much!
